use nanbox::JsValue;

// Stub for `__esc_dispatch` which is normally generated by Cranelift/LLVM
// codegen in the final binary. During tests, this symbol must be provided to
// satisfy the `extern "C"` declaration in `runtime::rt_api`.
#[unsafe(no_mangle)]
extern "C" fn __esc_dispatch(_func_idx: i32, _argc: i32, _argv: *const u64) -> u64 {
    // Return NaN-boxed undefined
    0x7FF8_0004_0000_0000_u64
}

// === Helper functions ===

/// Helper to create a test string JsValue from a &str.
/// Layout mirrors `runtime::string_ops::RtString { data: String }`.
fn test_make_string(s: &str) -> JsValue {
    #[repr(C)]
    struct TestString {
        data: String,
    }
    let rt_str = Box::new(TestString {
        data: s.to_string(),
    });
    let raw_ptr = Box::into_raw(rt_str) as *const ();
    JsValue::string(raw_ptr)
}

/// Helper to extract string data from a JsValue for assertions.
fn test_extract_string(val: &JsValue) -> Option<String> {
    #[repr(C)]
    struct TestString {
        data: String,
    }
    if let Some(ptr) = val.as_string() {
        if ptr.is_null() {
            return Some(String::new());
        }
        let rt_str = unsafe { &*(ptr as *const TestString) };
        Some(rt_str.data.clone())
    } else {
        None
    }
}

/// Helper to create a TaggedObj<JsObject> for tests that need plain objects.
fn make_tagged_plain_object() -> u64 {
    runtime::rt_api::__esc_rt_create_object()
}

// ========================================================================
// Registry tests
// ========================================================================

#[test]
fn test_registry_new_empty() {
    let reg = crate::registry::BuiltinRegistry::new();
    assert!(reg.is_empty());
    assert_eq!(reg.len(), 0);
}

#[test]
fn test_registry_with_defaults() {
    let reg = crate::registry::BuiltinRegistry::with_defaults();
    assert!(!reg.is_empty());
    assert_eq!(reg.len(), 6);
    assert!(reg.contains("isNaN"));
    assert!(reg.contains("isFinite"));
    assert!(reg.contains("parseInt"));
    assert!(reg.contains("parseFloat"));
    assert!(reg.contains("encodeURIComponent"));
    assert!(reg.contains("decodeURIComponent"));
}

#[test]
fn test_registry_default_trait() {
    let reg = crate::registry::BuiltinRegistry::default();
    assert_eq!(reg.len(), 6);
}

#[test]
fn test_registry_lookup_exists() {
    let reg = crate::registry::BuiltinRegistry::with_defaults();
    let is_nan = reg.get("isNaN");
    assert!(is_nan.is_some());
}

#[test]
fn test_registry_lookup_missing() {
    let reg = crate::registry::BuiltinRegistry::with_defaults();
    assert!(reg.get("nonexistent").is_none());
    assert!(!reg.contains("nonexistent"));
}

#[test]
fn test_registry_register_custom() {
    let mut reg = crate::registry::BuiltinRegistry::new();
    fn my_fn(_args: &[JsValue]) -> JsValue {
        JsValue::int(42)
    }
    reg.register("myFunc", my_fn);
    assert!(reg.contains("myFunc"));
    assert_eq!(reg.len(), 1);

    let func = reg.get("myFunc").unwrap();
    let result = func(&[]);
    assert_eq!(result.as_int(), Some(42));
}

#[test]
fn test_registry_register_overwrite() {
    let mut reg = crate::registry::BuiltinRegistry::new();
    fn fn_a(_args: &[JsValue]) -> JsValue {
        JsValue::int(1)
    }
    fn fn_b(_args: &[JsValue]) -> JsValue {
        JsValue::int(2)
    }
    reg.register("f", fn_a);
    reg.register("f", fn_b);
    assert_eq!(reg.len(), 1);

    let func = reg.get("f").unwrap();
    let result = func(&[]);
    assert_eq!(result.as_int(), Some(2));
}

// === Builtin function tests ===

#[test]
fn test_builtin_is_nan_with_nan() {
    let reg = crate::registry::BuiltinRegistry::with_defaults();
    let is_nan = reg.get("isNaN").unwrap();
    let result = is_nan(&[JsValue::number(f64::NAN)]);
    assert_eq!(result.as_bool(), Some(true));
}

#[test]
fn test_builtin_is_nan_with_number() {
    let reg = crate::registry::BuiltinRegistry::with_defaults();
    let is_nan = reg.get("isNaN").unwrap();
    let result = is_nan(&[JsValue::number(42.0)]);
    assert_eq!(result.as_bool(), Some(false));
}

#[test]
fn test_builtin_is_nan_with_undefined() {
    let reg = crate::registry::BuiltinRegistry::with_defaults();
    let is_nan = reg.get("isNaN").unwrap();
    let result = is_nan(&[JsValue::undefined()]);
    assert_eq!(result.as_bool(), Some(true));
}

#[test]
fn test_builtin_is_nan_no_args() {
    let reg = crate::registry::BuiltinRegistry::with_defaults();
    let is_nan = reg.get("isNaN").unwrap();
    let result = is_nan(&[]);
    assert_eq!(result.as_bool(), Some(true));
}

#[test]
fn test_builtin_is_finite_with_finite() {
    let reg = crate::registry::BuiltinRegistry::with_defaults();
    let is_finite = reg.get("isFinite").unwrap();
    let result = is_finite(&[JsValue::number(42.0)]);
    assert_eq!(result.as_bool(), Some(true));
}

#[test]
fn test_builtin_is_finite_with_infinity() {
    let reg = crate::registry::BuiltinRegistry::with_defaults();
    let is_finite = reg.get("isFinite").unwrap();
    let result = is_finite(&[JsValue::number(f64::INFINITY)]);
    assert_eq!(result.as_bool(), Some(false));
}

#[test]
fn test_builtin_is_finite_with_nan() {
    let reg = crate::registry::BuiltinRegistry::with_defaults();
    let is_finite = reg.get("isFinite").unwrap();
    let result = is_finite(&[JsValue::number(f64::NAN)]);
    assert_eq!(result.as_bool(), Some(false));
}

#[test]
fn test_builtin_is_finite_with_int() {
    let reg = crate::registry::BuiltinRegistry::with_defaults();
    let is_finite = reg.get("isFinite").unwrap();
    let result = is_finite(&[JsValue::int(42)]);
    assert_eq!(result.as_bool(), Some(true));
}

#[test]
fn test_builtin_parse_int_from_int() {
    let reg = crate::registry::BuiltinRegistry::with_defaults();
    let parse_int = reg.get("parseInt").unwrap();
    let result = parse_int(&[JsValue::int(42)]);
    assert_eq!(result.as_int(), Some(42));
}

#[test]
fn test_builtin_parse_int_from_float() {
    let reg = crate::registry::BuiltinRegistry::with_defaults();
    let parse_int = reg.get("parseInt").unwrap();
    let result = parse_int(&[JsValue::number(3.9)]);
    assert_eq!(result.as_number(), Some(3.0));
}

#[test]
fn test_builtin_parse_int_from_undefined() {
    let reg = crate::registry::BuiltinRegistry::with_defaults();
    let parse_int = reg.get("parseInt").unwrap();
    let result = parse_int(&[JsValue::undefined()]);
    assert!(result.as_number().unwrap().is_nan());
}

#[test]
fn test_builtin_parse_int_string_decimal() {
    let reg = crate::registry::BuiltinRegistry::with_defaults();
    let parse_int = reg.get("parseInt").unwrap();
    let result = parse_int(&[test_make_string("42")]);
    assert_eq!(result.as_number(), Some(42.0));
}

#[test]
fn test_builtin_parse_int_string_hex() {
    let reg = crate::registry::BuiltinRegistry::with_defaults();
    let parse_int = reg.get("parseInt").unwrap();
    let result = parse_int(&[test_make_string("0xFF")]);
    assert_eq!(result.as_number(), Some(255.0));
}

#[test]
fn test_builtin_parse_int_radix_2() {
    let reg = crate::registry::BuiltinRegistry::with_defaults();
    let parse_int = reg.get("parseInt").unwrap();
    let result = parse_int(&[test_make_string("1010"), JsValue::int(2)]);
    assert_eq!(result.as_number(), Some(10.0));
}

#[test]
fn test_builtin_parse_int_radix_16() {
    let reg = crate::registry::BuiltinRegistry::with_defaults();
    let parse_int = reg.get("parseInt").unwrap();
    let result = parse_int(&[test_make_string("ff"), JsValue::int(16)]);
    assert_eq!(result.as_number(), Some(255.0));
}

#[test]
fn test_builtin_parse_int_leading_whitespace() {
    let reg = crate::registry::BuiltinRegistry::with_defaults();
    let parse_int = reg.get("parseInt").unwrap();
    let result = parse_int(&[test_make_string("  42")]);
    assert_eq!(result.as_number(), Some(42.0));
}

#[test]
fn test_builtin_parse_int_negative() {
    let reg = crate::registry::BuiltinRegistry::with_defaults();
    let parse_int = reg.get("parseInt").unwrap();
    let result = parse_int(&[test_make_string("-10")]);
    assert_eq!(result.as_number(), Some(-10.0));
}

#[test]
fn test_builtin_parse_int_invalid_radix() {
    let reg = crate::registry::BuiltinRegistry::with_defaults();
    let parse_int = reg.get("parseInt").unwrap();
    let result = parse_int(&[test_make_string("10"), JsValue::int(1)]);
    assert!(result.as_number().unwrap().is_nan());
}

#[test]
fn test_builtin_parse_float_from_number() {
    let reg = crate::registry::BuiltinRegistry::with_defaults();
    let parse_float = reg.get("parseFloat").unwrap();
    let result = parse_float(&[JsValue::number(2.5)]);
    assert_eq!(result.as_number(), Some(2.5));
}

#[test]
fn test_builtin_parse_float_from_int() {
    let reg = crate::registry::BuiltinRegistry::with_defaults();
    let parse_float = reg.get("parseFloat").unwrap();
    let result = parse_float(&[JsValue::int(42)]);
    assert_eq!(result.as_number(), Some(42.0));
}

#[test]
fn test_builtin_parse_float_from_string() {
    let reg = crate::registry::BuiltinRegistry::with_defaults();
    let parse_float = reg.get("parseFloat").unwrap();
    let result = parse_float(&[test_make_string("2.5")]);
    assert_eq!(result.as_number(), Some(2.5));
}

#[test]
fn test_builtin_encode_uri_component() {
    let reg = crate::registry::BuiltinRegistry::with_defaults();
    let encode = reg.get("encodeURIComponent").unwrap();
    let result = encode(&[test_make_string("hello world")]);
    assert_eq!(
        test_extract_string(&result),
        Some("hello%20world".to_string())
    );
}

#[test]
fn test_builtin_encode_uri_component_special() {
    let reg = crate::registry::BuiltinRegistry::with_defaults();
    let encode = reg.get("encodeURIComponent").unwrap();
    let result = encode(&[test_make_string("a=b&c=d")]);
    assert_eq!(
        test_extract_string(&result),
        Some("a%3Db%26c%3Dd".to_string())
    );
}

#[test]
fn test_builtin_decode_uri_component() {
    let reg = crate::registry::BuiltinRegistry::with_defaults();
    let decode = reg.get("decodeURIComponent").unwrap();
    let result = decode(&[test_make_string("hello%20world")]);
    assert_eq!(
        test_extract_string(&result),
        Some("hello world".to_string())
    );
}

// ========================================================================
// Error type tests
// ========================================================================

#[test]
fn test_error_kind_error_name() {
    assert_eq!(crate::error_types::JsErrorKind::Error.name(), "Error");
}

#[test]
fn test_error_kind_type_error_name() {
    assert_eq!(
        crate::error_types::JsErrorKind::TypeError.name(),
        "TypeError"
    );
}

#[test]
fn test_error_kind_range_error_name() {
    assert_eq!(
        crate::error_types::JsErrorKind::RangeError.name(),
        "RangeError"
    );
}

#[test]
fn test_error_kind_reference_error_name() {
    assert_eq!(
        crate::error_types::JsErrorKind::ReferenceError.name(),
        "ReferenceError"
    );
}

#[test]
fn test_error_kind_syntax_error_name() {
    assert_eq!(
        crate::error_types::JsErrorKind::SyntaxError.name(),
        "SyntaxError"
    );
}

#[test]
fn test_error_kind_uri_error_name() {
    assert_eq!(crate::error_types::JsErrorKind::URIError.name(), "URIError");
}

#[test]
fn test_error_kind_eval_error_name() {
    assert_eq!(
        crate::error_types::JsErrorKind::EvalError.name(),
        "EvalError"
    );
}

#[test]
fn test_error_kind_all_names_unique() {
    use crate::error_types::JsErrorKind;
    let kinds = [
        JsErrorKind::Error,
        JsErrorKind::TypeError,
        JsErrorKind::RangeError,
        JsErrorKind::ReferenceError,
        JsErrorKind::SyntaxError,
        JsErrorKind::URIError,
        JsErrorKind::EvalError,
        JsErrorKind::AggregateError,
    ];
    let names: Vec<&str> = kinds.iter().map(|k| k.name()).collect();
    let mut unique = names.clone();
    unique.sort();
    unique.dedup();
    assert_eq!(names.len(), unique.len());
}

#[test]
fn test_error_kind_equality() {
    use crate::error_types::JsErrorKind;
    assert_eq!(JsErrorKind::TypeError, JsErrorKind::TypeError);
    assert_ne!(JsErrorKind::TypeError, JsErrorKind::RangeError);
}

#[test]
fn test_error_kind_clone() {
    use crate::error_types::JsErrorKind;
    let original = JsErrorKind::SyntaxError;
    let cloned = original;
    assert_eq!(original, cloned);
}

#[test]
fn test_error_constructor_message() {
    let msg = test_make_string("something went wrong");
    let err = crate::error_types::error(&[msg]);
    let result = crate::error_types::error_message(&[err]);
    assert_eq!(
        test_extract_string(&result),
        Some("something went wrong".to_string())
    );
}

#[test]
fn test_error_constructor_name() {
    let msg = test_make_string("test");
    let err = crate::error_types::type_error(&[msg]);
    let result = crate::error_types::error_name(&[err]);
    assert_eq!(test_extract_string(&result), Some("TypeError".to_string()));
}

#[test]
fn test_error_to_string() {
    let msg = test_make_string("bad value");
    let err = crate::error_types::type_error(&[msg]);
    let result = crate::error_types::error_to_string(&[err]);
    assert_eq!(
        test_extract_string(&result),
        Some("TypeError: bad value".to_string())
    );
}

#[test]
fn test_error_to_string_empty_message() {
    let err = crate::error_types::error(&[]);
    let result = crate::error_types::error_to_string(&[err]);
    assert_eq!(test_extract_string(&result), Some("Error".to_string()));
}

#[test]
fn test_error_get_kind() {
    let err = crate::error_types::range_error(&[test_make_string("out of range")]);
    let kind = crate::error_types::get_error_kind(&err);
    assert_eq!(kind, Some(crate::error_types::JsErrorKind::RangeError));
}

#[test]
fn test_all_error_constructors() {
    use crate::error_types::*;
    let msg = test_make_string("test");

    let e = error(&[msg]);
    assert_eq!(get_error_kind(&e), Some(JsErrorKind::Error));

    let msg = test_make_string("test");
    let e = type_error(&[msg]);
    assert_eq!(get_error_kind(&e), Some(JsErrorKind::TypeError));

    let msg = test_make_string("test");
    let e = range_error(&[msg]);
    assert_eq!(get_error_kind(&e), Some(JsErrorKind::RangeError));

    let msg = test_make_string("test");
    let e = reference_error(&[msg]);
    assert_eq!(get_error_kind(&e), Some(JsErrorKind::ReferenceError));

    let msg = test_make_string("test");
    let e = syntax_error(&[msg]);
    assert_eq!(get_error_kind(&e), Some(JsErrorKind::SyntaxError));

    let msg = test_make_string("test");
    let e = uri_error(&[msg]);
    assert_eq!(get_error_kind(&e), Some(JsErrorKind::URIError));

    let msg = test_make_string("test");
    let e = eval_error(&[msg]);
    assert_eq!(get_error_kind(&e), Some(JsErrorKind::EvalError));
}

// ========================================================================
// Boolean tests
// ========================================================================

#[test]
fn test_boolean_call_falsy_null() {
    let result = crate::boolean::boolean_call(&[JsValue::null()]);
    assert_eq!(result.as_bool(), Some(false));
}

#[test]
fn test_boolean_call_falsy_undefined() {
    let result = crate::boolean::boolean_call(&[JsValue::undefined()]);
    assert_eq!(result.as_bool(), Some(false));
}

#[test]
fn test_boolean_call_falsy_false() {
    let result = crate::boolean::boolean_call(&[JsValue::bool(false)]);
    assert_eq!(result.as_bool(), Some(false));
}

#[test]
fn test_boolean_call_falsy_zero() {
    let result = crate::boolean::boolean_call(&[JsValue::int(0)]);
    assert_eq!(result.as_bool(), Some(false));
}

#[test]
fn test_boolean_call_falsy_nan() {
    let result = crate::boolean::boolean_call(&[JsValue::number(f64::NAN)]);
    assert_eq!(result.as_bool(), Some(false));
}

#[test]
fn test_boolean_call_truthy_true() {
    let result = crate::boolean::boolean_call(&[JsValue::bool(true)]);
    assert_eq!(result.as_bool(), Some(true));
}

#[test]
fn test_boolean_call_truthy_nonzero() {
    let result = crate::boolean::boolean_call(&[JsValue::int(1)]);
    assert_eq!(result.as_bool(), Some(true));
}

#[test]
fn test_boolean_call_truthy_object() {
    let result = crate::boolean::boolean_call(&[JsValue::object(std::ptr::null())]);
    assert_eq!(result.as_bool(), Some(true));
}

#[test]
fn test_boolean_call_no_args() {
    let result = crate::boolean::boolean_call(&[]);
    assert_eq!(result.as_bool(), Some(false));
}

// ========================================================================
// Math tests
// ========================================================================

#[test]
fn test_math_abs_positive() {
    let result = crate::math::abs(&[JsValue::number(42.0)]);
    assert_eq!(result.as_number(), Some(42.0));
}

#[test]
fn test_math_abs_negative() {
    let result = crate::math::abs(&[JsValue::number(-7.5)]);
    assert_eq!(result.as_number(), Some(7.5));
}

#[test]
fn test_math_abs_nan() {
    let result = crate::math::abs(&[JsValue::number(f64::NAN)]);
    assert!(result.as_number().unwrap().is_nan());
}

#[test]
fn test_math_abs_no_args() {
    let result = crate::math::abs(&[]);
    assert!(result.as_number().unwrap().is_nan());
}

#[test]
fn test_math_abs_int_arg() {
    let result = crate::math::abs(&[JsValue::int(-5)]);
    assert_eq!(result.as_number(), Some(5.0));
}

#[test]
fn test_math_floor() {
    assert_eq!(
        crate::math::floor(&[JsValue::number(4.9)]).as_number(),
        Some(4.0)
    );
    assert_eq!(
        crate::math::floor(&[JsValue::number(-4.1)]).as_number(),
        Some(-5.0)
    );
}

#[test]
fn test_math_ceil() {
    assert_eq!(
        crate::math::ceil(&[JsValue::number(4.1)]).as_number(),
        Some(5.0)
    );
    assert_eq!(
        crate::math::ceil(&[JsValue::number(-4.9)]).as_number(),
        Some(-4.0)
    );
}

#[test]
fn test_math_round_normal() {
    assert_eq!(
        crate::math::round(&[JsValue::number(4.4)]).as_number(),
        Some(4.0)
    );
    assert_eq!(
        crate::math::round(&[JsValue::number(4.6)]).as_number(),
        Some(5.0)
    );
}

#[test]
fn test_math_round_half_rounds_up() {
    assert_eq!(
        crate::math::round(&[JsValue::number(0.5)]).as_number(),
        Some(1.0)
    );
    assert_eq!(
        crate::math::round(&[JsValue::number(2.5)]).as_number(),
        Some(3.0)
    );
}

#[test]
fn test_math_round_negative_half() {
    assert_eq!(
        crate::math::round(&[JsValue::number(-0.5)]).as_number(),
        Some(0.0)
    );
}

#[test]
fn test_math_max_basic() {
    let result = crate::math::max(&[
        JsValue::number(1.0),
        JsValue::number(3.0),
        JsValue::number(2.0),
    ]);
    assert_eq!(result.as_number(), Some(3.0));
}

#[test]
fn test_math_max_empty() {
    let result = crate::math::max(&[]);
    assert_eq!(result.as_number(), Some(f64::NEG_INFINITY));
}

#[test]
fn test_math_max_with_nan() {
    let result = crate::math::max(&[JsValue::number(1.0), JsValue::number(f64::NAN)]);
    assert!(result.as_number().unwrap().is_nan());
}

#[test]
fn test_math_max_with_int() {
    let result = crate::math::max(&[JsValue::int(5), JsValue::int(10)]);
    assert_eq!(result.as_number(), Some(10.0));
}

#[test]
fn test_math_min_basic() {
    let result = crate::math::min(&[
        JsValue::number(1.0),
        JsValue::number(3.0),
        JsValue::number(2.0),
    ]);
    assert_eq!(result.as_number(), Some(1.0));
}

#[test]
fn test_math_min_empty() {
    let result = crate::math::min(&[]);
    assert_eq!(result.as_number(), Some(f64::INFINITY));
}

#[test]
fn test_math_min_with_nan() {
    let result = crate::math::min(&[JsValue::number(1.0), JsValue::number(f64::NAN)]);
    assert!(result.as_number().unwrap().is_nan());
}

#[test]
fn test_math_sqrt() {
    assert_eq!(
        crate::math::sqrt(&[JsValue::number(9.0)]).as_number(),
        Some(3.0)
    );
    assert_eq!(
        crate::math::sqrt(&[JsValue::number(0.0)]).as_number(),
        Some(0.0)
    );
}

#[test]
fn test_math_sqrt_negative() {
    let result = crate::math::sqrt(&[JsValue::number(-1.0)]);
    assert!(result.as_number().unwrap().is_nan());
}

#[test]
fn test_math_pow() {
    assert_eq!(
        crate::math::pow(&[JsValue::number(2.0), JsValue::number(3.0)]).as_number(),
        Some(8.0)
    );
    assert_eq!(
        crate::math::pow(&[JsValue::number(5.0), JsValue::number(0.0)]).as_number(),
        Some(1.0)
    );
}

#[test]
fn test_math_sign_positive() {
    assert_eq!(
        crate::math::sign(&[JsValue::number(42.0)]).as_number(),
        Some(1.0)
    );
}

#[test]
fn test_math_sign_negative() {
    assert_eq!(
        crate::math::sign(&[JsValue::number(-42.0)]).as_number(),
        Some(-1.0)
    );
}

#[test]
fn test_math_sign_zero() {
    assert_eq!(
        crate::math::sign(&[JsValue::number(0.0)]).as_number(),
        Some(0.0)
    );
}

#[test]
fn test_math_sign_nan() {
    let result = crate::math::sign(&[JsValue::number(f64::NAN)]);
    assert!(result.as_number().unwrap().is_nan());
}

#[test]
fn test_math_trunc() {
    assert_eq!(
        crate::math::trunc(&[JsValue::number(4.9)]).as_number(),
        Some(4.0)
    );
    assert_eq!(
        crate::math::trunc(&[JsValue::number(-4.9)]).as_number(),
        Some(-4.0)
    );
}

#[test]
fn test_math_log() {
    let result = crate::math::log(&[JsValue::number(std::f64::consts::E)]);
    let n = result.as_number().unwrap();
    assert!((n - 1.0).abs() < 1e-10);
}

#[test]
fn test_math_sin() {
    let result = crate::math::sin(&[JsValue::number(0.0)]);
    assert_eq!(result.as_number(), Some(0.0));
}

#[test]
fn test_math_cos() {
    let result = crate::math::cos(&[JsValue::number(0.0)]);
    assert_eq!(result.as_number(), Some(1.0));
}

#[test]
fn test_math_random_in_range() {
    let result = crate::math::random(&[]);
    let n = result.as_number().unwrap();
    assert!(
        (0.0..1.0).contains(&n),
        "Math.random() = {n}, expected [0, 1)"
    );
}

#[test]
fn test_math_constants() {
    assert!((crate::math::PI - std::f64::consts::PI).abs() < f64::EPSILON);
    assert!((crate::math::E - std::f64::consts::E).abs() < f64::EPSILON);
    assert!((crate::math::LN2 - std::f64::consts::LN_2).abs() < f64::EPSILON);
    assert!((crate::math::LN10 - std::f64::consts::LN_10).abs() < f64::EPSILON);
    assert!((crate::math::LOG2E - std::f64::consts::LOG2_E).abs() < f64::EPSILON);
    assert!((crate::math::LOG10E - std::f64::consts::LOG10_E).abs() < f64::EPSILON);
    assert!((crate::math::SQRT2 - std::f64::consts::SQRT_2).abs() < f64::EPSILON);
}

#[test]
fn test_math_to_f64_bool_coercion() {
    assert_eq!(crate::math::to_f64(&JsValue::bool(true)), 1.0);
    assert_eq!(crate::math::to_f64(&JsValue::bool(false)), 0.0);
}

#[test]
fn test_math_to_f64_null_coercion() {
    assert_eq!(crate::math::to_f64(&JsValue::null()), 0.0);
}

#[test]
fn test_math_to_f64_undefined_is_nan() {
    assert!(crate::math::to_f64(&JsValue::undefined()).is_nan());
}

// ========================================================================
// Number tests
// ========================================================================

#[test]
fn test_number_is_integer_true_for_int() {
    let result = crate::number::is_integer(&[JsValue::int(42)]);
    assert_eq!(result.as_bool(), Some(true));
}

#[test]
fn test_number_is_integer_true_for_whole_number() {
    let result = crate::number::is_integer(&[JsValue::number(5.0)]);
    assert_eq!(result.as_bool(), Some(true));
}

#[test]
fn test_number_is_integer_false_for_float() {
    let result = crate::number::is_integer(&[JsValue::number(2.5)]);
    assert_eq!(result.as_bool(), Some(false));
}

#[test]
fn test_number_is_integer_false_for_infinity() {
    let result = crate::number::is_integer(&[JsValue::number(f64::INFINITY)]);
    assert_eq!(result.as_bool(), Some(false));
}

#[test]
fn test_number_is_integer_false_for_nan() {
    let result = crate::number::is_integer(&[JsValue::number(f64::NAN)]);
    assert_eq!(result.as_bool(), Some(false));
}

#[test]
fn test_number_is_finite_true() {
    assert_eq!(
        crate::number::is_finite(&[JsValue::number(42.0)]).as_bool(),
        Some(true)
    );
    assert_eq!(
        crate::number::is_finite(&[JsValue::int(0)]).as_bool(),
        Some(true)
    );
}

#[test]
fn test_number_is_finite_false() {
    assert_eq!(
        crate::number::is_finite(&[JsValue::number(f64::INFINITY)]).as_bool(),
        Some(false)
    );
    assert_eq!(
        crate::number::is_finite(&[JsValue::number(f64::NAN)]).as_bool(),
        Some(false)
    );
}

#[test]
fn test_number_is_finite_non_number() {
    assert_eq!(
        crate::number::is_finite(&[JsValue::bool(true)]).as_bool(),
        Some(false)
    );
    assert_eq!(
        crate::number::is_finite(&[JsValue::null()]).as_bool(),
        Some(false)
    );
}

#[test]
fn test_number_is_nan_true() {
    let result = crate::number::is_nan(&[JsValue::number(f64::NAN)]);
    assert_eq!(result.as_bool(), Some(true));
}

#[test]
fn test_number_is_nan_false() {
    assert_eq!(
        crate::number::is_nan(&[JsValue::number(42.0)]).as_bool(),
        Some(false)
    );
    assert_eq!(
        crate::number::is_nan(&[JsValue::undefined()]).as_bool(),
        Some(false)
    );
    assert_eq!(
        crate::number::is_nan(&[JsValue::int(0)]).as_bool(),
        Some(false)
    );
}

#[test]
fn test_number_is_safe_integer_true() {
    assert_eq!(
        crate::number::is_safe_integer(&[JsValue::int(42)]).as_bool(),
        Some(true)
    );
    assert_eq!(
        crate::number::is_safe_integer(&[JsValue::number(crate::number::MAX_SAFE_INTEGER)])
            .as_bool(),
        Some(true)
    );
}

#[test]
fn test_number_is_safe_integer_false() {
    assert_eq!(
        crate::number::is_safe_integer(&[JsValue::number(crate::number::MAX_SAFE_INTEGER + 1.0)])
            .as_bool(),
        Some(false)
    );
    assert_eq!(
        crate::number::is_safe_integer(&[JsValue::number(f64::INFINITY)]).as_bool(),
        Some(false)
    );
}

#[test]
fn test_number_parse_int_from_int() {
    let result = crate::number::parse_int(&[JsValue::int(42)]);
    assert_eq!(result.as_int(), Some(42));
}

#[test]
fn test_number_parse_int_from_float() {
    let result = crate::number::parse_int(&[JsValue::number(3.99)]);
    assert_eq!(result.as_number(), Some(3.0));
}

#[test]
fn test_number_parse_int_from_undefined() {
    let result = crate::number::parse_int(&[JsValue::undefined()]);
    assert!(result.as_number().unwrap().is_nan());
}

#[test]
fn test_number_parse_float_from_number() {
    let result = crate::number::parse_float(&[JsValue::number(2.5)]);
    assert_eq!(result.as_number(), Some(2.5));
}

#[test]
fn test_number_parse_float_from_int() {
    let result = crate::number::parse_float(&[JsValue::int(42)]);
    assert_eq!(result.as_number(), Some(42.0));
}

#[test]
fn test_number_constants() {
    assert_eq!(crate::number::MAX_SAFE_INTEGER, 9_007_199_254_740_991.0);
    assert_eq!(crate::number::MIN_SAFE_INTEGER, -9_007_199_254_740_991.0);
    assert_eq!(crate::number::EPSILON, f64::EPSILON);
    assert_eq!(crate::number::MAX_VALUE, f64::MAX);
    assert_eq!(crate::number::MIN_VALUE, 5e-324);
    assert_eq!(crate::number::POSITIVE_INFINITY, f64::INFINITY);
    assert_eq!(crate::number::NEGATIVE_INFINITY, f64::NEG_INFINITY);
    assert!(crate::number::NAN.is_nan());
}

// ========================================================================
// String tests
// ========================================================================

#[test]
fn test_string_length_basic() {
    let s = test_make_string("hello");
    let result = crate::string::length(&[s]);
    assert_eq!(result.as_int(), Some(5));
}

#[test]
fn test_string_length_empty() {
    let s = test_make_string("");
    let result = crate::string::length(&[s]);
    assert_eq!(result.as_int(), Some(0));
}

#[test]
fn test_string_index_of_found() {
    let s = test_make_string("hello world");
    let needle = test_make_string("world");
    let result = crate::string::index_of(&[s, needle]);
    assert_eq!(result.as_int(), Some(6));
}

#[test]
fn test_string_index_of_not_found() {
    let s = test_make_string("hello world");
    let needle = test_make_string("xyz");
    let result = crate::string::index_of(&[s, needle]);
    assert_eq!(result.as_int(), Some(-1));
}

#[test]
fn test_string_char_at_valid() {
    let s = test_make_string("abc");
    let result = crate::string::char_at(&[s, JsValue::int(1)]);
    assert_eq!(test_extract_string(&result), Some("b".to_string()));
}

#[test]
fn test_string_char_at_oob() {
    let s = test_make_string("abc");
    let result = crate::string::char_at(&[s, JsValue::int(10)]);
    assert_eq!(test_extract_string(&result), Some(String::new()));
}

#[test]
fn test_string_trim() {
    let s = test_make_string("  hello  ");
    let result = crate::string::trim(&[s]);
    assert_eq!(test_extract_string(&result), Some("hello".to_string()));
}

#[test]
fn test_string_to_lower_case() {
    let s = test_make_string("Hello World");
    let result = crate::string::to_lower_case(&[s]);
    assert_eq!(
        test_extract_string(&result),
        Some("hello world".to_string())
    );
}

#[test]
fn test_string_to_upper_case() {
    let s = test_make_string("Hello World");
    let result = crate::string::to_upper_case(&[s]);
    assert_eq!(
        test_extract_string(&result),
        Some("HELLO WORLD".to_string())
    );
}

#[test]
fn test_string_includes_found() {
    let s = test_make_string("hello world");
    let needle = test_make_string("world");
    let result = crate::string::includes(&[s, needle]);
    assert_eq!(result.as_bool(), Some(true));
}

#[test]
fn test_string_includes_not_found() {
    let s = test_make_string("hello world");
    let needle = test_make_string("xyz");
    let result = crate::string::includes(&[s, needle]);
    assert_eq!(result.as_bool(), Some(false));
}

#[test]
fn test_string_starts_with() {
    let s = test_make_string("hello world");
    let prefix = test_make_string("hello");
    let result = crate::string::starts_with(&[s, prefix]);
    assert_eq!(result.as_bool(), Some(true));
}

#[test]
fn test_string_ends_with() {
    let s = test_make_string("hello world");
    let suffix = test_make_string("world");
    let result = crate::string::ends_with(&[s, suffix]);
    assert_eq!(result.as_bool(), Some(true));
}

#[test]
fn test_string_repeat() {
    let s = test_make_string("ab");
    let result = crate::string::repeat(&[s, JsValue::int(3)]);
    assert_eq!(test_extract_string(&result), Some("ababab".to_string()));
}

#[test]
fn test_string_replace() {
    let s = test_make_string("hello world");
    let search = test_make_string("world");
    let replacement = test_make_string("rust");
    let result = crate::string::replace(&[s, search, replacement]);
    assert_eq!(test_extract_string(&result), Some("hello rust".to_string()));
}

#[test]
fn test_string_replace_first_only() {
    let s = test_make_string("aaa");
    let search = test_make_string("a");
    let replacement = test_make_string("b");
    let result = crate::string::replace(&[s, search, replacement]);
    assert_eq!(test_extract_string(&result), Some("baa".to_string()));
}

#[test]
fn test_string_concat() {
    let a = test_make_string("hello");
    let b = test_make_string(" ");
    let c = test_make_string("world");
    let result = crate::string::concat(&[a, b, c]);
    assert_eq!(
        test_extract_string(&result),
        Some("hello world".to_string())
    );
}

#[test]
fn test_string_pad_start() {
    let s = test_make_string("5");
    let result = crate::string::pad_start(&[s, JsValue::int(3), test_make_string("0")]);
    assert_eq!(test_extract_string(&result), Some("005".to_string()));
}

#[test]
fn test_string_slice_basic() {
    let s = test_make_string("hello world");
    let result = crate::string::slice(&[s, JsValue::int(0), JsValue::int(5)]);
    assert_eq!(test_extract_string(&result), Some("hello".to_string()));
}

#[test]
fn test_string_slice_negative() {
    let s = test_make_string("hello world");
    let result = crate::string::slice(&[s, JsValue::int(-5)]);
    assert_eq!(test_extract_string(&result), Some("world".to_string()));
}

// --- New String tests (D1) ---

#[test]
fn test_string_split_basic() {
    let s = test_make_string("a,b,c");
    let sep = test_make_string(",");
    let result = crate::string::split(&[s, sep]);
    assert_eq!(result.as_int(), Some(3));
}

#[test]
fn test_string_split_empty_separator() {
    let s = test_make_string("abc");
    let sep = test_make_string("");
    let result = crate::string::split(&[s, sep]);
    // Splitting on "" produces chars (4 parts for "abc": "", "a", "b", "c")
    assert!(result.as_int().unwrap() > 0);
}

#[test]
fn test_string_split_with_limit() {
    let s = test_make_string("a,b,c,d");
    let sep = test_make_string(",");
    let result = crate::string::split(&[s, sep, JsValue::int(2)]);
    assert_eq!(result.as_int(), Some(2));
}

#[test]
fn test_string_substring_basic() {
    let s = test_make_string("hello world");
    let result = crate::string::substring(&[s, JsValue::int(0), JsValue::int(5)]);
    assert_eq!(test_extract_string(&result), Some("hello".to_string()));
}

#[test]
fn test_string_substring_swaps_args() {
    let s = test_make_string("hello");
    // substring(3, 1) should swap to substring(1, 3)
    let result = crate::string::substring(&[s, JsValue::int(3), JsValue::int(1)]);
    assert_eq!(test_extract_string(&result), Some("el".to_string()));
}

#[test]
fn test_string_replace_all() {
    let s = test_make_string("aaa");
    let search = test_make_string("a");
    let replacement = test_make_string("b");
    let result = crate::string::replace_all(&[s, search, replacement]);
    assert_eq!(test_extract_string(&result), Some("bbb".to_string()));
}

#[test]
fn test_string_at_positive() {
    let s = test_make_string("hello");
    let result = crate::string::at(&[s, JsValue::int(1)]);
    assert_eq!(test_extract_string(&result), Some("e".to_string()));
}

#[test]
fn test_string_at_negative() {
    let s = test_make_string("hello");
    let result = crate::string::at(&[s, JsValue::int(-1)]);
    assert_eq!(test_extract_string(&result), Some("o".to_string()));
}

#[test]
fn test_string_at_out_of_range() {
    let s = test_make_string("hi");
    let result = crate::string::at(&[s, JsValue::int(10)]);
    assert!(result.is_undefined());
}

#[test]
fn test_string_trim_start() {
    let s = test_make_string("  hello  ");
    let result = crate::string::trim_start(&[s]);
    assert_eq!(test_extract_string(&result), Some("hello  ".to_string()));
}

#[test]
fn test_string_trim_end() {
    let s = test_make_string("  hello  ");
    let result = crate::string::trim_end(&[s]);
    assert_eq!(test_extract_string(&result), Some("  hello".to_string()));
}

#[test]
fn test_string_code_point_at() {
    let s = test_make_string("ABC");
    let result = crate::string::code_point_at(&[s, JsValue::int(0)]);
    assert_eq!(result.as_int(), Some(65)); // 'A' = 65
}

#[test]
fn test_string_code_point_at_oob() {
    let s = test_make_string("A");
    let result = crate::string::code_point_at(&[s, JsValue::int(5)]);
    assert!(result.is_undefined());
}

#[test]
fn test_string_from_code_point() {
    let result = crate::string::from_code_point(&[JsValue::int(72), JsValue::int(105)]);
    assert_eq!(test_extract_string(&result), Some("Hi".to_string()));
}

#[test]
fn test_string_search_found() {
    let s = test_make_string("hello world");
    let pat = test_make_string("world");
    let result = crate::string::search(&[s, pat]);
    assert_eq!(result.as_int(), Some(6));
}

#[test]
fn test_string_search_not_found() {
    let s = test_make_string("hello");
    let pat = test_make_string("xyz");
    let result = crate::string::search(&[s, pat]);
    assert_eq!(result.as_int(), Some(-1));
}

#[test]
fn test_string_match_found() {
    let s = test_make_string("hello world");
    let pat = test_make_string("world");
    let result = crate::string::match_str(&[s, pat]);
    assert_eq!(test_extract_string(&result), Some("world".to_string()));
}

#[test]
fn test_string_match_not_found() {
    let s = test_make_string("hello");
    let pat = test_make_string("xyz");
    let result = crate::string::match_str(&[s, pat]);
    assert!(result.is_null());
}

#[test]
fn test_string_match_all_count() {
    let s = test_make_string("abcabc");
    let pat = test_make_string("abc");
    let result = crate::string::match_all(&[s, pat]);
    assert_eq!(result.as_int(), Some(2));
}

#[test]
fn test_string_pad_end() {
    let s = test_make_string("5");
    let result = crate::string::pad_end(&[s, JsValue::int(3), test_make_string("0")]);
    assert_eq!(test_extract_string(&result), Some("500".to_string()));
}

// ========================================================================
// Array tests
// ========================================================================

#[test]
fn test_array_is_array_object() {
    let obj = JsValue::object(std::ptr::null());
    let result = crate::array::is_array(&[obj]);
    assert_eq!(result.as_bool(), Some(true));
}

#[test]
fn test_array_is_array_non_object() {
    assert_eq!(
        crate::array::is_array(&[JsValue::number(42.0)]).as_bool(),
        Some(false)
    );
    assert_eq!(
        crate::array::is_array(&[JsValue::undefined()]).as_bool(),
        Some(false)
    );
}

#[test]
fn test_array_of() {
    let arr = crate::array::of(&[JsValue::int(1), JsValue::int(2), JsValue::int(3)]);
    assert!(arr.is_object());
    let len = crate::array::length(&[arr]);
    assert_eq!(len.as_int(), Some(3));
}

#[test]
fn test_array_push_pop() {
    let arr = crate::array::of(&[JsValue::int(1)]);
    crate::array::push(&[arr, JsValue::int(2), JsValue::int(3)]);
    assert_eq!(crate::array::length(&[arr]).as_int(), Some(3));

    let popped = crate::array::pop(&[arr]);
    assert_eq!(popped.as_int(), Some(3));
    assert_eq!(crate::array::length(&[arr]).as_int(), Some(2));
}

#[test]
fn test_array_pop_empty() {
    let arr = crate::array::of(&[]);
    let result = crate::array::pop(&[arr]);
    assert!(result.is_undefined());
}

#[test]
fn test_array_shift_unshift() {
    let arr = crate::array::of(&[JsValue::int(2), JsValue::int(3)]);

    // unshift adds to front
    crate::array::unshift(&[arr, JsValue::int(1)]);
    assert_eq!(crate::array::length(&[arr]).as_int(), Some(3));

    // shift removes from front
    let shifted = crate::array::shift(&[arr]);
    assert_eq!(shifted.as_int(), Some(1));
    assert_eq!(crate::array::length(&[arr]).as_int(), Some(2));
}

#[test]
fn test_array_shift_empty() {
    let arr = crate::array::of(&[]);
    let result = crate::array::shift(&[arr]);
    assert!(result.is_undefined());
}

#[test]
fn test_array_index_of_found() {
    let arr = crate::array::of(&[JsValue::int(10), JsValue::int(20), JsValue::int(30)]);
    let result = crate::array::index_of(&[arr, JsValue::int(20)]);
    assert_eq!(result.as_int(), Some(1));
}

#[test]
fn test_array_index_of_not_found() {
    let arr = crate::array::of(&[JsValue::int(10), JsValue::int(20)]);
    let result = crate::array::index_of(&[arr, JsValue::int(99)]);
    assert_eq!(result.as_int(), Some(-1));
}

#[test]
fn test_array_includes_true() {
    let arr = crate::array::of(&[JsValue::int(1), JsValue::int(2), JsValue::int(3)]);
    let result = crate::array::includes(&[arr, JsValue::int(2)]);
    assert_eq!(result.as_bool(), Some(true));
}

#[test]
fn test_array_includes_false() {
    let arr = crate::array::of(&[JsValue::int(1), JsValue::int(2)]);
    let result = crate::array::includes(&[arr, JsValue::int(99)]);
    assert_eq!(result.as_bool(), Some(false));
}

#[test]
fn test_array_join_default() {
    let arr = crate::array::of(&[JsValue::int(1), JsValue::int(2), JsValue::int(3)]);
    let result = crate::array::join(&[arr]);
    assert_eq!(test_extract_string(&result), Some("1,2,3".to_string()));
}

#[test]
fn test_array_join_custom_separator() {
    let arr = crate::array::of(&[JsValue::int(1), JsValue::int(2)]);
    let result = crate::array::join(&[arr, test_make_string(" - ")]);
    assert_eq!(test_extract_string(&result), Some("1 - 2".to_string()));
}

#[test]
fn test_array_slice_basic() {
    let arr = crate::array::of(&[
        JsValue::int(1),
        JsValue::int(2),
        JsValue::int(3),
        JsValue::int(4),
    ]);
    let sliced = crate::array::slice(&[arr, JsValue::int(1), JsValue::int(3)]);
    assert_eq!(crate::array::length(&[sliced]).as_int(), Some(2));
}

#[test]
fn test_array_slice_negative() {
    let arr = crate::array::of(&[JsValue::int(1), JsValue::int(2), JsValue::int(3)]);
    let sliced = crate::array::slice(&[arr, JsValue::int(-2)]);
    assert_eq!(crate::array::length(&[sliced]).as_int(), Some(2));
}

#[test]
fn test_array_reverse() {
    let arr = crate::array::of(&[JsValue::int(1), JsValue::int(2), JsValue::int(3)]);
    crate::array::reverse(&[arr]);
    let elems = crate::array::test_extract_array(&arr).unwrap();
    assert_eq!(elems[0].as_int(), Some(3));
    assert_eq!(elems[1].as_int(), Some(2));
    assert_eq!(elems[2].as_int(), Some(1));
}

#[test]
fn test_array_sort_numeric() {
    let arr = crate::array::of(&[JsValue::int(3), JsValue::int(1), JsValue::int(2)]);
    crate::array::sort(&[arr]);
    let elems = crate::array::test_extract_array(&arr).unwrap();
    assert_eq!(elems[0].as_int(), Some(1));
    assert_eq!(elems[1].as_int(), Some(2));
    assert_eq!(elems[2].as_int(), Some(3));
}

#[test]
fn test_array_splice_delete() {
    let arr = crate::array::of(&[JsValue::int(1), JsValue::int(2), JsValue::int(3)]);
    let deleted = crate::array::splice(&[arr, JsValue::int(1), JsValue::int(1)]);
    assert_eq!(crate::array::length(&[arr]).as_int(), Some(2));
    assert_eq!(crate::array::length(&[deleted]).as_int(), Some(1));
}

#[test]
fn test_array_splice_insert() {
    let arr = crate::array::of(&[JsValue::int(1), JsValue::int(3)]);
    crate::array::splice(&[arr, JsValue::int(1), JsValue::int(0), JsValue::int(2)]);
    assert_eq!(crate::array::length(&[arr]).as_int(), Some(3));
    let elems = crate::array::test_extract_array(&arr).unwrap();
    assert_eq!(elems[1].as_int(), Some(2));
}

#[test]
fn test_array_fill() {
    let arr = crate::array::of(&[JsValue::int(0), JsValue::int(0), JsValue::int(0)]);
    crate::array::fill(&[arr, JsValue::int(7)]);
    let elems = crate::array::test_extract_array(&arr).unwrap();
    assert!(elems.iter().all(|v| v.as_int() == Some(7)));
}

#[test]
fn test_array_concat() {
    let a = crate::array::of(&[JsValue::int(1)]);
    let b = crate::array::of(&[JsValue::int(2)]);
    let result = crate::array::concat(&[a, b]);
    assert_eq!(crate::array::length(&[result]).as_int(), Some(2));
}

#[test]
fn test_array_flat() {
    // Create inner array
    let inner = crate::array::of(&[JsValue::int(2), JsValue::int(3)]);
    // Create outer array with [1, [2, 3]]
    let outer = crate::array::of(&[JsValue::int(1), inner]);
    let flattened = crate::array::flat(&[outer]);
    assert_eq!(crate::array::length(&[flattened]).as_int(), Some(3));
}

#[test]
fn test_array_from_value() {
    let result = crate::array::from(&[JsValue::int(42)]);
    assert_eq!(crate::array::length(&[result]).as_int(), Some(1));
}

#[test]
fn test_array_from_array() {
    let original = crate::array::of(&[JsValue::int(1), JsValue::int(2)]);
    let copy = crate::array::from(&[original]);
    assert_eq!(crate::array::length(&[copy]).as_int(), Some(2));
}

#[test]
fn test_array_map_returns_copy() {
    let arr = crate::array::of(&[JsValue::int(1), JsValue::int(2)]);
    let mapped = crate::array::map(&[arr]);
    assert_eq!(crate::array::length(&[mapped]).as_int(), Some(2));
}

#[test]
fn test_array_filter_returns_copy() {
    let arr = crate::array::of(&[JsValue::int(1), JsValue::int(2)]);
    let filtered = crate::array::filter(&[arr]);
    assert_eq!(crate::array::length(&[filtered]).as_int(), Some(2));
}

#[test]
fn test_array_reduce_with_initial() {
    let arr = crate::array::of(&[JsValue::int(1), JsValue::int(2)]);
    // reduce(this, callback, initialValue) — returns initialValue without callback
    let result = crate::array::reduce(&[arr, JsValue::undefined(), JsValue::int(99)]);
    assert_eq!(result.as_int(), Some(99));
}

#[test]
fn test_array_reduce_without_initial() {
    let arr = crate::array::of(&[JsValue::int(42)]);
    let result = crate::array::reduce(&[arr]);
    assert_eq!(result.as_int(), Some(42));
}

#[test]
fn test_array_find_returns_undefined() {
    let result = crate::array::find(&[]);
    assert!(result.is_undefined());
}

#[test]
fn test_array_find_index_returns_negative() {
    let result = crate::array::find_index(&[]);
    assert_eq!(result.as_int(), Some(-1));
}

#[test]
fn test_array_some_returns_false() {
    let result = crate::array::some(&[]);
    assert_eq!(result.as_bool(), Some(false));
}

#[test]
fn test_array_every_returns_true() {
    let result = crate::array::every(&[]);
    assert_eq!(result.as_bool(), Some(true));
}

#[test]
fn test_array_copy_within() {
    let arr = crate::array::of(&[
        JsValue::int(1),
        JsValue::int(2),
        JsValue::int(3),
        JsValue::int(4),
    ]);
    crate::array::copy_within(&[arr, JsValue::int(0), JsValue::int(2)]);
    let elems = crate::array::test_extract_array(&arr).unwrap();
    assert_eq!(elems[0].as_int(), Some(3));
    assert_eq!(elems[1].as_int(), Some(4));
}

// ========================================================================
// Object tests
// ========================================================================

#[test]
fn test_object_keys_returns_zero() {
    let result = crate::object::object_keys(&[JsValue::object(std::ptr::null())]);
    assert_eq!(result.as_int(), Some(0));
}

#[test]
fn test_object_values_returns_zero() {
    let result = crate::object::object_values(&[JsValue::object(std::ptr::null())]);
    assert_eq!(result.as_int(), Some(0));
}

#[test]
fn test_object_entries_returns_zero() {
    let result = crate::object::object_entries(&[JsValue::object(std::ptr::null())]);
    assert_eq!(result.as_int(), Some(0));
}

#[test]
fn test_object_create_returns_object() {
    let result = crate::object::object_create(&[JsValue::null()]);
    assert!(result.is_object());
}

#[test]
fn test_object_assign_returns_target() {
    let target = JsValue::object(std::ptr::null());
    let result = crate::object::object_assign(&[target]);
    assert!(result.is_object());
}

#[test]
fn test_object_define_property_returns_object() {
    let obj = JsValue::object(std::ptr::null());
    let result = crate::object::object_define_property(&[obj]);
    assert!(result.is_object());
}

#[test]
fn test_object_freeze_and_is_frozen() {
    let obj_bits = make_tagged_plain_object();
    let obj = JsValue::from_raw_bits(obj_bits);
    assert_eq!(
        crate::object::object_is_frozen(&[obj]).as_bool(),
        Some(false)
    );
    crate::object::object_freeze(&[obj]);
    assert_eq!(
        crate::object::object_is_frozen(&[obj]).as_bool(),
        Some(true)
    );
}

#[test]
fn test_object_seal_and_is_sealed() {
    let obj_bits = make_tagged_plain_object();
    let obj = JsValue::from_raw_bits(obj_bits);
    assert_eq!(
        crate::object::object_is_sealed(&[obj]).as_bool(),
        Some(false)
    );
    crate::object::object_seal(&[obj]);
    assert_eq!(
        crate::object::object_is_sealed(&[obj]).as_bool(),
        Some(true)
    );
}

#[test]
fn test_object_freeze_implies_sealed() {
    let obj_bits = make_tagged_plain_object();
    let obj = JsValue::from_raw_bits(obj_bits);
    crate::object::object_freeze(&[obj]);
    assert_eq!(
        crate::object::object_is_sealed(&[obj]).as_bool(),
        Some(true)
    );
}

#[test]
fn test_object_get_prototype_of_returns_null() {
    let result = crate::object::object_get_prototype_of(&[JsValue::object(std::ptr::null())]);
    assert!(result.is_null());
}

#[test]
fn test_object_has_own_returns_false() {
    let result = crate::object::object_has_own(&[JsValue::object(std::ptr::null())]);
    assert_eq!(result.as_bool(), Some(false));
}

#[test]
fn test_object_is_frozen_non_object() {
    // Non-objects are vacuously frozen
    let result = crate::object::object_is_frozen(&[JsValue::int(42)]);
    assert_eq!(result.as_bool(), Some(true));
}

// ========================================================================
// Function tests
// ========================================================================

#[test]
fn test_function_bind_returns_function() {
    let func = JsValue::object(std::ptr::null());
    let result = crate::function::bind(&[func]);
    assert!(result.is_object());
}

#[test]
fn test_function_call_returns_undefined() {
    let result = crate::function::call(&[]);
    assert!(result.is_undefined());
}

#[test]
fn test_function_apply_returns_undefined() {
    let result = crate::function::apply(&[]);
    assert!(result.is_undefined());
}

// ========================================================================
// JSON tests
// ========================================================================

#[test]
fn test_json_stringify_number() {
    let result = crate::json::stringify(&[JsValue::int(42)]);
    assert_eq!(test_extract_string(&result), Some("42".to_string()));
}

#[test]
fn test_json_stringify_float() {
    let result = crate::json::stringify(&[JsValue::number(2.5)]);
    assert_eq!(test_extract_string(&result), Some("2.5".to_string()));
}

#[test]
fn test_json_stringify_string() {
    let s = test_make_string("hello");
    let result = crate::json::stringify(&[s]);
    assert_eq!(test_extract_string(&result), Some("\"hello\"".to_string()));
}

#[test]
fn test_json_stringify_bool_true() {
    let result = crate::json::stringify(&[JsValue::bool(true)]);
    assert_eq!(test_extract_string(&result), Some("true".to_string()));
}

#[test]
fn test_json_stringify_bool_false() {
    let result = crate::json::stringify(&[JsValue::bool(false)]);
    assert_eq!(test_extract_string(&result), Some("false".to_string()));
}

#[test]
fn test_json_stringify_null() {
    let result = crate::json::stringify(&[JsValue::null()]);
    assert_eq!(test_extract_string(&result), Some("null".to_string()));
}

#[test]
fn test_json_stringify_undefined() {
    let result = crate::json::stringify(&[JsValue::undefined()]);
    assert!(result.is_undefined());
}

#[test]
fn test_json_stringify_nan() {
    let result = crate::json::stringify(&[JsValue::number(f64::NAN)]);
    assert_eq!(test_extract_string(&result), Some("null".to_string()));
}

#[test]
fn test_json_stringify_infinity() {
    let result = crate::json::stringify(&[JsValue::number(f64::INFINITY)]);
    assert_eq!(test_extract_string(&result), Some("null".to_string()));
}

#[test]
fn test_json_stringify_object() {
    let obj = JsValue::object(std::ptr::null());
    let result = crate::json::stringify(&[obj]);
    assert_eq!(test_extract_string(&result), Some("{}".to_string()));
}

#[test]
fn test_json_parse_number() {
    let s = test_make_string("42");
    let result = crate::json::parse(&[s]);
    assert_eq!(result.as_number(), Some(42.0));
}

#[test]
fn test_json_parse_float() {
    let s = test_make_string("2.5");
    let result = crate::json::parse(&[s]);
    assert_eq!(result.as_number(), Some(2.5));
}

#[test]
fn test_json_parse_bool_true() {
    let s = test_make_string("true");
    let result = crate::json::parse(&[s]);
    assert_eq!(result.as_bool(), Some(true));
}

#[test]
fn test_json_parse_bool_false() {
    let s = test_make_string("false");
    let result = crate::json::parse(&[s]);
    assert_eq!(result.as_bool(), Some(false));
}

#[test]
fn test_json_parse_null() {
    let s = test_make_string("null");
    let result = crate::json::parse(&[s]);
    assert!(result.is_null());
}

#[test]
fn test_json_parse_string() {
    let s = test_make_string("\"hello\"");
    let result = crate::json::parse(&[s]);
    assert_eq!(test_extract_string(&result), Some("hello".to_string()));
}

#[test]
fn test_json_parse_array() {
    let s = test_make_string("[1, 2, 3]");
    let result = crate::json::parse(&[s]);
    // Returns int count of array elements
    assert_eq!(result.as_int(), Some(3));
}

#[test]
fn test_json_parse_object() {
    let s = test_make_string("{\"key\": \"value\"}");
    let result = crate::json::parse(&[s]);
    assert!(result.is_object());
}

#[test]
fn test_json_parse_nested_object() {
    let s = test_make_string("{\"a\": {\"b\": 1}}");
    let result = crate::json::parse(&[s]);
    assert!(result.is_object());
}

#[test]
fn test_json_parse_non_string_returns_undefined() {
    let result = crate::json::parse(&[JsValue::int(42)]);
    assert!(result.is_undefined());
}

#[test]
fn test_json_parse_escaped_string() {
    let s = test_make_string("\"hello\\nworld\"");
    let result = crate::json::parse(&[s]);
    assert_eq!(
        test_extract_string(&result),
        Some("hello\nworld".to_string())
    );
}

// ========================================================================
// Promise tests
// ========================================================================

#[test]
fn test_promise_resolve() {
    let p = crate::promise::resolve(&[JsValue::int(42)]);
    assert!(p.is_object());
    assert_eq!(
        crate::promise::get_state(&p),
        Some(crate::promise::PromiseState::Fulfilled)
    );
    assert_eq!(crate::promise::get_value(&p).unwrap().as_int(), Some(42));
}

#[test]
fn test_promise_reject() {
    let p = crate::promise::reject(&[test_make_string("error")]);
    assert!(p.is_object());
    assert_eq!(
        crate::promise::get_state(&p),
        Some(crate::promise::PromiseState::Rejected)
    );
}

#[test]
fn test_promise_then_returns_pending() {
    let p = crate::promise::then(&[]);
    assert_eq!(
        crate::promise::get_state(&p),
        Some(crate::promise::PromiseState::Pending)
    );
}

#[test]
fn test_promise_catch_returns_pending() {
    let p = crate::promise::catch(&[]);
    assert_eq!(
        crate::promise::get_state(&p),
        Some(crate::promise::PromiseState::Pending)
    );
}

#[test]
fn test_promise_finally_fulfilled_preserves_value() {
    // finally on fulfilled: callback "called" (no-op in sync model),
    // original value preserved.
    let p = crate::promise::resolve(&[JsValue::int(42)]);
    let result = crate::promise::finally_method(&[p]);
    assert_eq!(
        crate::promise::get_state(&result),
        Some(crate::promise::PromiseState::Fulfilled)
    );
    assert_eq!(
        crate::promise::get_value(&result).unwrap().as_int(),
        Some(42)
    );
}

#[test]
fn test_promise_finally_rejected_preserves_reason() {
    // finally on rejected: callback "called", original reason preserved.
    let p = crate::promise::reject(&[JsValue::int(99)]);
    let result = crate::promise::finally_method(&[p]);
    assert_eq!(
        crate::promise::get_state(&result),
        Some(crate::promise::PromiseState::Rejected)
    );
    assert_eq!(
        crate::promise::get_value(&result).unwrap().as_int(),
        Some(99)
    );
}

#[test]
fn test_promise_finally_pending_returns_pending() {
    // finally on pending: returns pending.
    let p = crate::promise::then(&[]); // pending promise
    let result = crate::promise::finally_method(&[p]);
    assert_eq!(
        crate::promise::get_state(&result),
        Some(crate::promise::PromiseState::Pending)
    );
}

#[test]
fn test_promise_finally_no_callback_fulfilled_passthrough() {
    // finally with no callback arg on a fulfilled promise: pass through.
    let p = crate::promise::resolve(&[JsValue::int(7)]);
    let result = crate::promise::finally_method(&[p]);
    assert_eq!(
        crate::promise::get_state(&result),
        Some(crate::promise::PromiseState::Fulfilled)
    );
    assert_eq!(
        crate::promise::get_value(&result).unwrap().as_int(),
        Some(7)
    );
}

#[test]
fn test_promise_finally_no_callback_rejected_passthrough() {
    // finally with no callback arg on a rejected promise: pass through.
    let p = crate::promise::reject(&[JsValue::int(13)]);
    let result = crate::promise::finally_method(&[p]);
    assert_eq!(
        crate::promise::get_state(&result),
        Some(crate::promise::PromiseState::Rejected)
    );
    assert_eq!(
        crate::promise::get_value(&result).unwrap().as_int(),
        Some(13)
    );
}

#[test]
fn test_promise_finally_no_args_returns_pending() {
    // finally with no args at all (no this): returns pending (defensive).
    let result = crate::promise::finally_method(&[]);
    assert_eq!(
        crate::promise::get_state(&result),
        Some(crate::promise::PromiseState::Pending)
    );
}

#[test]
fn test_promise_finally_non_promise_this_returns_pending() {
    // finally with a non-promise this: returns pending (defensive).
    let result = crate::promise::finally_method(&[JsValue::int(5)]);
    assert_eq!(
        crate::promise::get_state(&result),
        Some(crate::promise::PromiseState::Pending)
    );
}

// ========================================================================
// Promise.withResolvers tests
// ========================================================================

#[test]
fn test_promise_with_resolvers_returns_array_with_promise() {
    // withResolvers returns a 3-element array where first element is a pending promise.
    let result = crate::promise::with_resolvers(&[]);
    let components = crate::promise::get_resolvers_components(&result);
    assert!(components.is_some());
    let (promise, _resolve_fn, _reject_fn) = components.unwrap();
    assert_eq!(
        crate::promise::get_state(&promise),
        Some(crate::promise::PromiseState::Pending)
    );
}

#[test]
fn test_promise_with_resolvers_resolve_is_undefined() {
    // In the synchronous model, resolve_fn is a placeholder (undefined).
    let result = crate::promise::with_resolvers(&[]);
    let (_, resolve_fn, _) = crate::promise::get_resolvers_components(&result).unwrap();
    assert!(resolve_fn.is_undefined());
}

#[test]
fn test_promise_with_resolvers_reject_is_undefined() {
    // In the synchronous model, reject_fn is a placeholder (undefined).
    let result = crate::promise::with_resolvers(&[]);
    let (_, _, reject_fn) = crate::promise::get_resolvers_components(&result).unwrap();
    assert!(reject_fn.is_undefined());
}

#[test]
fn test_promise_all_empty_resolves() {
    // Promise.all([]) resolves with an empty array.
    let p = crate::promise::all(&[]);
    assert_eq!(
        crate::promise::get_state(&p),
        Some(crate::promise::PromiseState::Fulfilled)
    );
}

#[test]
fn test_promise_race_empty_stays_pending() {
    // Promise.race([]) stays pending forever per spec.
    let p = crate::promise::race(&[]);
    assert_eq!(
        crate::promise::get_state(&p),
        Some(crate::promise::PromiseState::Pending)
    );
}

#[test]
fn test_promise_any_empty_rejects() {
    // Promise.any([]) rejects with AggregateError.
    let p = crate::promise::any(&[]);
    assert_eq!(
        crate::promise::get_state(&p),
        Some(crate::promise::PromiseState::Rejected)
    );
}

// ========================================================================
// Promise.race tests
// ========================================================================

/// Helper: wrap an array of promise JsValues into a single array arg for combinators.
fn make_promise_array(promises: Vec<JsValue>) -> JsValue {
    crate::array::of(&promises)
}

#[test]
fn test_promise_race_first_fulfilled_wins() {
    let p1 = crate::promise::resolve(&[JsValue::int(10)]);
    let p2 = crate::promise::resolve(&[JsValue::int(20)]);
    let arr = make_promise_array(vec![p1, p2]);
    let result = crate::promise::race(&[arr]);
    assert_eq!(
        crate::promise::get_state(&result),
        Some(crate::promise::PromiseState::Fulfilled)
    );
    assert_eq!(
        crate::promise::get_value(&result).unwrap().as_int(),
        Some(10)
    );
}

#[test]
fn test_promise_race_first_rejected_wins() {
    let p1 = crate::promise::reject(&[JsValue::int(99)]);
    let p2 = crate::promise::resolve(&[JsValue::int(20)]);
    let arr = make_promise_array(vec![p1, p2]);
    let result = crate::promise::race(&[arr]);
    assert_eq!(
        crate::promise::get_state(&result),
        Some(crate::promise::PromiseState::Rejected)
    );
    assert_eq!(
        crate::promise::get_value(&result).unwrap().as_int(),
        Some(99)
    );
}

#[test]
fn test_promise_race_skips_pending_finds_settled() {
    let pending = crate::promise::then(&[]); // pending promise
    let fulfilled = crate::promise::resolve(&[JsValue::int(42)]);
    let arr = make_promise_array(vec![pending, fulfilled]);
    let result = crate::promise::race(&[arr]);
    assert_eq!(
        crate::promise::get_state(&result),
        Some(crate::promise::PromiseState::Fulfilled)
    );
    assert_eq!(
        crate::promise::get_value(&result).unwrap().as_int(),
        Some(42)
    );
}

#[test]
fn test_promise_race_all_pending_returns_pending() {
    let p1 = crate::promise::then(&[]);
    let p2 = crate::promise::then(&[]);
    let arr = make_promise_array(vec![p1, p2]);
    let result = crate::promise::race(&[arr]);
    assert_eq!(
        crate::promise::get_state(&result),
        Some(crate::promise::PromiseState::Pending)
    );
}

// ========================================================================
// Promise.allSettled tests
// ========================================================================

#[test]
fn test_promise_all_settled_all_fulfilled() {
    let p1 = crate::promise::resolve(&[JsValue::int(1)]);
    let p2 = crate::promise::resolve(&[JsValue::int(2)]);
    let arr = make_promise_array(vec![p1, p2]);
    let result = crate::promise::all_settled(&[arr]);
    assert_eq!(
        crate::promise::get_state(&result),
        Some(crate::promise::PromiseState::Fulfilled)
    );
    let results = crate::promise::get_result_array(&result);
    assert!(results.is_some());
    assert_eq!(results.unwrap().len(), 2);
}

#[test]
fn test_promise_all_settled_all_rejected() {
    let p1 = crate::promise::reject(&[JsValue::int(100)]);
    let p2 = crate::promise::reject(&[JsValue::int(200)]);
    let arr = make_promise_array(vec![p1, p2]);
    let result = crate::promise::all_settled(&[arr]);
    assert_eq!(
        crate::promise::get_state(&result),
        Some(crate::promise::PromiseState::Fulfilled)
    );
    let results = crate::promise::get_result_array(&result).unwrap();
    assert_eq!(results.len(), 2);
}

#[test]
fn test_promise_all_settled_mixed() {
    let p1 = crate::promise::resolve(&[JsValue::int(1)]);
    let p2 = crate::promise::reject(&[JsValue::int(2)]);
    let arr = make_promise_array(vec![p1, p2]);
    let result = crate::promise::all_settled(&[arr]);
    assert_eq!(
        crate::promise::get_state(&result),
        Some(crate::promise::PromiseState::Fulfilled)
    );
    let results = crate::promise::get_result_array(&result).unwrap();
    assert_eq!(results.len(), 2);

    // First entry should be fulfilled
    let (status1, val1) = crate::promise::get_settlement_entry(&results[0]).unwrap();
    assert!(status1.is_string());
    assert_eq!(val1.as_int(), Some(1));

    // Second entry should be rejected
    let (status2, val2) = crate::promise::get_settlement_entry(&results[1]).unwrap();
    assert!(status2.is_string());
    assert_eq!(val2.as_int(), Some(2));
}

#[test]
fn test_promise_all_settled_empty_resolves_with_empty_array() {
    let arr = make_promise_array(vec![]);
    let result = crate::promise::all_settled(&[arr]);
    assert_eq!(
        crate::promise::get_state(&result),
        Some(crate::promise::PromiseState::Fulfilled)
    );
    let results = crate::promise::get_result_array(&result).unwrap();
    assert_eq!(results.len(), 0);
}

#[test]
fn test_promise_all_settled_pending_returns_pending() {
    let p1 = crate::promise::resolve(&[JsValue::int(1)]);
    let p2 = crate::promise::then(&[]); // pending
    let arr = make_promise_array(vec![p1, p2]);
    let result = crate::promise::all_settled(&[arr]);
    assert_eq!(
        crate::promise::get_state(&result),
        Some(crate::promise::PromiseState::Pending)
    );
}

// ========================================================================
// Promise.any tests
// ========================================================================

#[test]
fn test_promise_any_first_fulfilled_wins() {
    let p1 = crate::promise::resolve(&[JsValue::int(42)]);
    let p2 = crate::promise::reject(&[JsValue::int(99)]);
    let arr = make_promise_array(vec![p1, p2]);
    let result = crate::promise::any(&[arr]);
    assert_eq!(
        crate::promise::get_state(&result),
        Some(crate::promise::PromiseState::Fulfilled)
    );
    assert_eq!(
        crate::promise::get_value(&result).unwrap().as_int(),
        Some(42)
    );
}

#[test]
fn test_promise_any_skips_rejected_finds_fulfilled() {
    let p1 = crate::promise::reject(&[JsValue::int(1)]);
    let p2 = crate::promise::reject(&[JsValue::int(2)]);
    let p3 = crate::promise::resolve(&[JsValue::int(3)]);
    let arr = make_promise_array(vec![p1, p2, p3]);
    let result = crate::promise::any(&[arr]);
    assert_eq!(
        crate::promise::get_state(&result),
        Some(crate::promise::PromiseState::Fulfilled)
    );
    assert_eq!(
        crate::promise::get_value(&result).unwrap().as_int(),
        Some(3)
    );
}

#[test]
fn test_promise_any_all_rejected_returns_aggregate_error() {
    let p1 = crate::promise::reject(&[JsValue::int(10)]);
    let p2 = crate::promise::reject(&[JsValue::int(20)]);
    let arr = make_promise_array(vec![p1, p2]);
    let result = crate::promise::any(&[arr]);
    assert_eq!(
        crate::promise::get_state(&result),
        Some(crate::promise::PromiseState::Rejected)
    );
    // The rejection value is an AggregateError
    let agg = crate::promise::get_value(&result).unwrap();
    let kind = crate::error_types::get_aggregate_error_kind(&agg);
    assert_eq!(kind, Some(crate::error_types::JsErrorKind::AggregateError));
}

#[test]
fn test_promise_any_empty_rejects_with_aggregate_error() {
    let arr = make_promise_array(vec![]);
    let result = crate::promise::any(&[arr]);
    assert_eq!(
        crate::promise::get_state(&result),
        Some(crate::promise::PromiseState::Rejected)
    );
    let agg = crate::promise::get_value(&result).unwrap();
    let kind = crate::error_types::get_aggregate_error_kind(&agg);
    assert_eq!(kind, Some(crate::error_types::JsErrorKind::AggregateError));
}

#[test]
fn test_promise_any_pending_returns_pending() {
    let p1 = crate::promise::reject(&[JsValue::int(1)]);
    let p2 = crate::promise::then(&[]); // pending
    let arr = make_promise_array(vec![p1, p2]);
    let result = crate::promise::any(&[arr]);
    assert_eq!(
        crate::promise::get_state(&result),
        Some(crate::promise::PromiseState::Pending)
    );
}

// ========================================================================
// Promise.all tests (additional)
// ========================================================================

#[test]
fn test_promise_all_all_fulfilled() {
    let p1 = crate::promise::resolve(&[JsValue::int(1)]);
    let p2 = crate::promise::resolve(&[JsValue::int(2)]);
    let p3 = crate::promise::resolve(&[JsValue::int(3)]);
    let arr = make_promise_array(vec![p1, p2, p3]);
    let result = crate::promise::all(&[arr]);
    assert_eq!(
        crate::promise::get_state(&result),
        Some(crate::promise::PromiseState::Fulfilled)
    );
    let values = crate::promise::get_result_array(&result).unwrap();
    assert_eq!(values.len(), 3);
    assert_eq!(values[0].as_int(), Some(1));
    assert_eq!(values[1].as_int(), Some(2));
    assert_eq!(values[2].as_int(), Some(3));
}

#[test]
fn test_promise_all_one_rejected() {
    let p1 = crate::promise::resolve(&[JsValue::int(1)]);
    let p2 = crate::promise::reject(&[JsValue::int(99)]);
    let arr = make_promise_array(vec![p1, p2]);
    let result = crate::promise::all(&[arr]);
    assert_eq!(
        crate::promise::get_state(&result),
        Some(crate::promise::PromiseState::Rejected)
    );
    assert_eq!(
        crate::promise::get_value(&result).unwrap().as_int(),
        Some(99)
    );
}

#[test]
fn test_promise_all_with_pending_returns_pending() {
    let p1 = crate::promise::resolve(&[JsValue::int(1)]);
    let p2 = crate::promise::then(&[]); // pending
    let arr = make_promise_array(vec![p1, p2]);
    let result = crate::promise::all(&[arr]);
    assert_eq!(
        crate::promise::get_state(&result),
        Some(crate::promise::PromiseState::Pending)
    );
}

// ========================================================================
// AggregateError tests
// ========================================================================

#[test]
fn test_aggregate_error_constructor() {
    let errors_array = crate::array::of(&[JsValue::int(1), JsValue::int(2)]);
    let msg = test_make_string("all failed");
    let agg = crate::error_types::aggregate_error(&[errors_array, msg]);
    assert!(agg.is_object());
    let kind = crate::error_types::get_aggregate_error_kind(&agg);
    assert_eq!(kind, Some(crate::error_types::JsErrorKind::AggregateError));
}

#[test]
fn test_aggregate_error_errors_property() {
    let errors_array = crate::array::of(&[JsValue::int(10), JsValue::int(20)]);
    let msg = test_make_string("multiple errors");
    let agg = crate::error_types::aggregate_error(&[errors_array, msg]);
    let errors = crate::error_types::get_aggregate_errors(&agg);
    assert!(errors.is_some());
    let errors_val = errors.unwrap();
    assert!(errors_val.is_object());
}

#[test]
fn test_aggregate_error_message_property() {
    let errors_array = crate::array::of(&[]);
    let msg = test_make_string("everything broke");
    let agg = crate::error_types::aggregate_error(&[errors_array, msg]);
    let msg_val = crate::error_types::get_aggregate_error_message(&agg);
    let extracted = test_extract_string(&msg_val);
    assert_eq!(extracted, Some("everything broke".to_string()));
}

#[test]
fn test_aggregate_error_is_error_subclass() {
    let errors_array = crate::array::of(&[]);
    let msg = test_make_string("test");
    let agg = crate::error_types::aggregate_error(&[errors_array, msg]);
    // AggregateError's kind name should be "AggregateError"
    let kind = crate::error_types::get_aggregate_error_kind(&agg);
    assert_eq!(kind, Some(crate::error_types::JsErrorKind::AggregateError));
    assert_eq!(
        crate::error_types::JsErrorKind::AggregateError.name(),
        "AggregateError"
    );
}

#[test]
fn test_aggregate_error_no_message() {
    let errors_array = crate::array::of(&[JsValue::int(1)]);
    let agg = crate::error_types::aggregate_error(&[errors_array]);
    let kind = crate::error_types::get_aggregate_error_kind(&agg);
    assert_eq!(kind, Some(crate::error_types::JsErrorKind::AggregateError));
    // Message should default to empty
    let msg_val = crate::error_types::get_aggregate_error_message(&agg);
    let extracted = test_extract_string(&msg_val);
    assert_eq!(extracted, Some(String::new()));
}

#[test]
fn test_aggregate_error_kind_name() {
    assert_eq!(
        crate::error_types::JsErrorKind::AggregateError.name(),
        "AggregateError"
    );
}

// ========================================================================
// Map tests
// ========================================================================

#[test]
fn test_map_new_empty() {
    let m = crate::map::map_new(&[]);
    assert_eq!(crate::map::size(&[m]).as_int(), Some(0));
}

#[test]
fn test_map_set_and_get() {
    let m = crate::map::map_new(&[]);
    crate::map::set(&[m, JsValue::int(1), JsValue::int(100)]);
    let val = crate::map::get(&[m, JsValue::int(1)]);
    assert_eq!(val.as_int(), Some(100));
}

#[test]
fn test_map_has() {
    let m = crate::map::map_new(&[]);
    crate::map::set(&[m, JsValue::int(42), JsValue::bool(true)]);
    assert_eq!(
        crate::map::has(&[m, JsValue::int(42)]).as_bool(),
        Some(true)
    );
    assert_eq!(
        crate::map::has(&[m, JsValue::int(99)]).as_bool(),
        Some(false)
    );
}

#[test]
fn test_map_delete() {
    let m = crate::map::map_new(&[]);
    crate::map::set(&[m, JsValue::int(1), JsValue::int(10)]);
    assert_eq!(crate::map::size(&[m]).as_int(), Some(1));
    let deleted = crate::map::delete(&[m, JsValue::int(1)]);
    assert_eq!(deleted.as_bool(), Some(true));
    assert_eq!(crate::map::size(&[m]).as_int(), Some(0));
}

#[test]
fn test_map_delete_missing() {
    let m = crate::map::map_new(&[]);
    let deleted = crate::map::delete(&[m, JsValue::int(99)]);
    assert_eq!(deleted.as_bool(), Some(false));
}

#[test]
fn test_map_clear() {
    let m = crate::map::map_new(&[]);
    crate::map::set(&[m, JsValue::int(1), JsValue::int(1)]);
    crate::map::set(&[m, JsValue::int(2), JsValue::int(2)]);
    assert_eq!(crate::map::size(&[m]).as_int(), Some(2));
    crate::map::clear(&[m]);
    assert_eq!(crate::map::size(&[m]).as_int(), Some(0));
}

#[test]
fn test_map_set_overwrite() {
    let m = crate::map::map_new(&[]);
    crate::map::set(&[m, JsValue::int(1), JsValue::int(10)]);
    crate::map::set(&[m, JsValue::int(1), JsValue::int(20)]);
    assert_eq!(crate::map::size(&[m]).as_int(), Some(1));
    assert_eq!(crate::map::get(&[m, JsValue::int(1)]).as_int(), Some(20));
}

// ========================================================================
// Set tests
// ========================================================================

#[test]
fn test_set_new_empty() {
    let s = crate::set::set_new(&[]);
    assert_eq!(crate::set::size(&[s]).as_int(), Some(0));
}

#[test]
fn test_set_add_and_has() {
    let s = crate::set::set_new(&[]);
    crate::set::add(&[s, JsValue::int(42)]);
    assert_eq!(
        crate::set::has(&[s, JsValue::int(42)]).as_bool(),
        Some(true)
    );
    assert_eq!(
        crate::set::has(&[s, JsValue::int(99)]).as_bool(),
        Some(false)
    );
}

#[test]
fn test_set_duplicates_ignored() {
    let s = crate::set::set_new(&[]);
    crate::set::add(&[s, JsValue::int(1)]);
    crate::set::add(&[s, JsValue::int(1)]);
    crate::set::add(&[s, JsValue::int(1)]);
    assert_eq!(crate::set::size(&[s]).as_int(), Some(1));
}

#[test]
fn test_set_delete() {
    let s = crate::set::set_new(&[]);
    crate::set::add(&[s, JsValue::int(1)]);
    let deleted = crate::set::delete(&[s, JsValue::int(1)]);
    assert_eq!(deleted.as_bool(), Some(true));
    assert_eq!(crate::set::size(&[s]).as_int(), Some(0));
}

#[test]
fn test_set_delete_missing() {
    let s = crate::set::set_new(&[]);
    let deleted = crate::set::delete(&[s, JsValue::int(99)]);
    assert_eq!(deleted.as_bool(), Some(false));
}

#[test]
fn test_set_clear() {
    let s = crate::set::set_new(&[]);
    crate::set::add(&[s, JsValue::int(1)]);
    crate::set::add(&[s, JsValue::int(2)]);
    crate::set::clear(&[s]);
    assert_eq!(crate::set::size(&[s]).as_int(), Some(0));
}

// ========================================================================
// Symbol tests
// ========================================================================

#[test]
fn test_well_known_symbol_descriptions() {
    use crate::symbol::WellKnownSymbol;
    assert_eq!(WellKnownSymbol::Iterator.description(), "Symbol.iterator");
    assert_eq!(
        WellKnownSymbol::ToPrimitive.description(),
        "Symbol.toPrimitive"
    );
    assert_eq!(
        WellKnownSymbol::ToStringTag.description(),
        "Symbol.toStringTag"
    );
    assert_eq!(
        WellKnownSymbol::HasInstance.description(),
        "Symbol.hasInstance"
    );
    assert_eq!(
        WellKnownSymbol::IsConcatSpreadable.description(),
        "Symbol.isConcatSpreadable"
    );
    assert_eq!(WellKnownSymbol::Species.description(), "Symbol.species");
}

#[test]
fn test_well_known_symbol_equality() {
    use crate::symbol::WellKnownSymbol;
    assert_eq!(WellKnownSymbol::Iterator, WellKnownSymbol::Iterator);
    assert_ne!(WellKnownSymbol::Iterator, WellKnownSymbol::ToPrimitive);
}

#[test]
fn test_well_known_symbol_all() {
    use crate::symbol::WellKnownSymbol;
    let all = WellKnownSymbol::all();
    assert_eq!(all.len(), 6);
    assert!(all.contains(&WellKnownSymbol::Iterator));
    assert!(all.contains(&WellKnownSymbol::Species));
}

#[test]
fn test_well_known_symbol_debug() {
    use crate::symbol::WellKnownSymbol;
    let s = format!("{:?}", WellKnownSymbol::Iterator);
    assert_eq!(s, "Iterator");
}

#[test]
fn test_well_known_symbol_hash() {
    use crate::symbol::WellKnownSymbol;
    use std::collections::HashSet;
    let mut set = HashSet::new();
    set.insert(WellKnownSymbol::Iterator);
    set.insert(WellKnownSymbol::Iterator);
    set.insert(WellKnownSymbol::Species);
    assert_eq!(set.len(), 2);
}

// ========================================================================
// Console tests
// ========================================================================

#[test]
fn test_console_log_does_not_panic() {
    crate::console::console_log(&[JsValue::int(42)]);
    crate::console::console_log(&[JsValue::number(2.5)]);
    crate::console::console_log(&[JsValue::bool(true)]);
    crate::console::console_log(&[JsValue::null()]);
    crate::console::console_log(&[JsValue::undefined()]);
    crate::console::console_log(&[]);
}

#[test]
fn test_console_error_does_not_panic() {
    crate::console::console_error(&[JsValue::int(1), JsValue::number(2.0)]);
}

#[test]
fn test_console_warn_does_not_panic() {
    crate::console::console_warn(&[JsValue::bool(false)]);
}

#[test]
fn test_console_debug_does_not_panic() {
    crate::console::console_debug(&[JsValue::null()]);
}

// ========================================================================
// process global object tests
// ========================================================================

#[test]
fn test_process_platform_is_non_empty() {
    let p = crate::process::platform();
    assert!(!p.is_empty(), "process.platform must be non-empty");
    // Must be one of the Node.js conventions
    assert!(
        ["linux", "darwin", "win32", "freebsd", "openbsd", "unknown"].contains(&p),
        "process.platform must use Node.js convention, got: {p}"
    );
}

#[test]
fn test_process_arch_is_non_empty() {
    let a = crate::process::arch();
    assert!(!a.is_empty(), "process.arch must be non-empty");
    // Must be one of the Node.js conventions
    assert!(
        ["x64", "arm64", "ia32", "arm", "unknown"].contains(&a),
        "process.arch must use Node.js convention, got: {a}"
    );
}

#[test]
fn test_process_version_starts_with_v() {
    let ver = crate::process::version();
    assert!(
        ver.starts_with('v'),
        "process.version must start with 'v', got: {ver}"
    );
    // Should contain a dot (semver)
    assert!(
        ver.contains('.'),
        "process.version must contain a dot, got: {ver}"
    );
}

#[test]
fn test_process_pid_is_positive() {
    let pid = crate::process::pid();
    assert!(
        pid > 0,
        "process.pid must be a positive integer, got: {pid}"
    );
}

#[test]
fn test_process_cwd_returns_non_empty() {
    let cwd = crate::process::cwd();
    assert!(
        !cwd.is_empty(),
        "process.cwd() must return a non-empty string"
    );
}

#[test]
fn test_process_argv_is_non_empty() {
    // In test context, host args_count returns the real process args
    let args = crate::process::argv();
    // The test runner itself should have at least 1 arg (the binary name)
    assert!(
        !args.is_empty(),
        "process.argv should have at least one element"
    );
}

#[test]
fn test_process_env_contains_path_or_home() {
    let env = crate::process::env_snapshot();
    let has_path = env.iter().any(|(k, _)| k == "PATH");
    let has_home = env.iter().any(|(k, _)| k == "HOME");
    assert!(
        has_path || has_home,
        "process.env should contain PATH or HOME"
    );
}

#[test]
fn test_process_env_snapshot_returns_pairs() {
    let env = crate::process::env_snapshot();
    assert!(
        !env.is_empty(),
        "process.env snapshot must contain at least one entry"
    );
    // Verify structure: each entry has non-empty key
    for (key, _val) in &env {
        assert!(
            !key.is_empty(),
            "environment variable key must not be empty"
        );
    }
}

#[test]
fn test_process_hrtime_returns_valid_pair() {
    let (seconds, nanoseconds) = crate::process::hrtime();
    // nanoseconds component must be < 1 billion
    assert!(
        nanoseconds < 1_000_000_000,
        "hrtime nanoseconds must be < 1e9, got: {nanoseconds}"
    );
    // seconds should be non-negative (monotonic clock)
    // seconds could be 0 right after boot, so we just check it's reasonable
    assert!(
        seconds > 0 || nanoseconds > 0,
        "hrtime must return a non-zero timestamp"
    );
}

#[test]
fn test_process_hrtime_is_monotonic() {
    let (s1, ns1) = crate::process::hrtime();
    // Do a small amount of work
    let _ = (0..1000).sum::<i32>();
    let (s2, ns2) = crate::process::hrtime();
    let total1 = s1 * 1_000_000_000 + ns1;
    let total2 = s2 * 1_000_000_000 + ns2;
    assert!(
        total2 >= total1,
        "hrtime must be monotonic: {total1} -> {total2}"
    );
}

#[test]
fn test_process_platform_matches_expected() {
    let p = crate::process::platform();
    // Verify we get the correct platform for the current system
    if cfg!(target_os = "linux") {
        assert_eq!(p, "linux");
    } else if cfg!(target_os = "macos") {
        assert_eq!(p, "darwin");
    } else if cfg!(target_os = "windows") {
        assert_eq!(p, "win32");
    }
}

#[test]
fn test_process_arch_matches_expected() {
    let a = crate::process::arch();
    // Verify we get the correct arch for the current system
    if cfg!(target_arch = "x86_64") {
        assert_eq!(a, "x64");
    } else if cfg!(target_arch = "aarch64") {
        assert_eq!(a, "arm64");
    }
}

// ========================================================================
// __filename / __dirname placeholder tests
// ========================================================================

#[test]
fn test_filename_dirname_are_recognized_globals() {
    // Verify that __filename and __dirname are recognized as builtin globals
    // by the desugar layer. They should resolve to empty strings for now.
    assert!(
        desugar::globals::is_builtin_global("process"),
        "process must be a builtin global"
    );
    // __filename and __dirname are resolved directly in expr.rs, not in
    // is_builtin_global — they are compile-time constants (empty strings).
    // We test their resolution via the process module's intended behavior.
}

#[test]
fn test_process_is_builtin_namespace() {
    assert!(
        desugar::globals::is_builtin_namespace("process"),
        "process must be a builtin namespace"
    );
}
